services:
  db:
    image: mysql:8.0.35
    container_name: ${APP_UID}_db
    restart: 'unless-stopped'
    user: root
    volumes:
      - ./lc/mysql/db:/var/lib/mysql
      # - ./lc/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./:/var/www
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    command: >
      --default-authentication-plugin=mysql_native_password
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO

  tribe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_UID}_tribe
    restart: 'unless-stopped'
    working_dir: /var/www/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${TRIBE_PORT}:80"
    volumes:
      - ./.env:/var/www/.env
      - ./api:/var/www/api
      - ./theme:/var/www/theme
      - ./config:/var/www/config
      - ./custom:/var/www/custom
      - ./uploads:/var/www/uploads
      - ./applications:/var/www/applications
      - ./config/phpmyadmin/config.inc.php:/var/www/phpmyadmin/config.inc.php
      - ./config/nginx:/etc/nginx/conf.d
    environment:
      - PHP_VERSION=7.4

networks:
  default:
    driver: bridge
    name: ${APP_UID}_network